general {
    lock_cmd = pidof hyprlock || hyprlock    # ロック用コマンド
    before_sleep_cmd = loginctl lock-session  # スリープ前のロック
    after_sleep_cmd = hyprctl dispatch dpms on  # スリープ復帰時に画面オン
    inhibit_sleep = 3   
}

listener {
    timeout = 60                                # 60秒（1分）
    on-timeout = [ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && brightnessctl -s set 10         # 電源つながってなければ現在の輝度を保存し、10%まで下げる
    on-resume = brightnessctl -r                # 操作再開時に元の輝度に戻す
}

listener {
    timeout = 300                                # 5分
    on-timeout = [ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && systemctl suspend-then-hibernate        # 電源つながってなければ画面ロック サスペンド
}

