-- lua/plugins/nvim-treesitter.lua
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "typescript",
      "json",
      "jsonc",
      "bash",
      "python",
      "java",
      "c",
      "cpp",
      "rust",
      "javascript",
      "lua",
      "yaml",
      "html",
      "css",
      "scss",
      "svelite",
      "graphql",
      "dockerfile",
      "git_config",
      "gitignore",
      "gitattributes",
      "gitcommit",
      "git_rebase",
      "make",
      "toml",
      "ini",
      "markdown",
      "markdown_inline",
      "regex",
      "sql",
      "diff",
      "vimdoc",
      "comment"
    },
    sync_install = true,
  },
}
